#!/usr/bin/env bash
SOURCE="${BASH_SOURCE[0]}"
while [ -L "$SOURCE" ]; do
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
HERE="$(cd -P "$(dirname "$SOURCE")" && pwd)"

export XDG_CONFIG_HOME="$HERE/config"
export XDG_DATA_HOME="$HERE/share"
export XDG_STATE_HOME="$HERE/state"
export XDG_CACHE_HOME="$HERE/cache"
export NVIM_APPNAME="vicodin"
export VIMRUNTIME="$HERE/runtime"
export PATH=$HERE/bin:$PATH

exec "$HERE/bin/nvim" "$@"
